### ISSUE TITLE
README - TWO errors for Japanese Cuisine

### ISSUE THREAD

**Issue by jbrucker** [J-Jullaphong/ku-international-cafe#13]
https://github.com/J-Jullaphong/ku-international-cafe/blob/c7fb14c1123df2e9bf08474035b3fafbc1ec953e/README.md?plain=1#L9

- Missing hyperlink to the actual menu section
- Careless about case of letters! I'm getting really annoyed by continued carelessness here.  Use a grammar checker.

**Comment by Kongkawee** [comment]
Case fixed.
